// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/engine_api.dart';
import 'api/init.dart';
import 'api/simple.dart';
import 'api/types.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 2019276971;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_uot_app',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<String> crateApiEngineApiEngineAcceptTransfer({
    required String transferId,
  });

  Future<String> crateApiEngineApiEngineCancelTransfer({
    required String transferId,
  });

  String crateApiEngineApiEngineDeviceId();

  String crateApiEngineApiEngineGetDevices();

  String crateApiEngineApiEngineGetEvents({required int limit});

  String crateApiEngineApiEngineGetProgress({required String transferId});

  String crateApiEngineApiEngineGetStreams();

  String crateApiEngineApiEngineGetTransfers();

  Future<String> crateApiEngineApiEngineInit();

  String crateApiEngineApiEngineLoadSettings();

  Future<String> crateApiEngineApiEnginePauseTransfer({
    required String transferId,
  });

  Future<String> crateApiEngineApiEngineResumeTransfer({
    required String transferId,
  });

  Future<String> crateApiEngineApiEngineSaveSettings({required String json});

  Future<String> crateApiEngineApiEngineSendClipboard({
    required String deviceId,
    required String text,
  });

  Future<String> crateApiEngineApiEngineSendFiles({
    required String deviceId,
    required List<String> filePaths,
  });

  Future<String> crateApiEngineApiEngineSetDeviceName({required String name});

  String crateApiEngineApiEngineState();

  Future<void> crateApiEngineApiEngineStop();

  String crateApiInitGetBuildInfo();

  int crateApiInitGetProtocolVersion();

  String crateApiInitGetVersion();

  String crateApiSimpleGreet({required String name});

  String crateApiInitHealthCheck();

  Future<void> crateApiSimpleInitApp();

  Future<PlatformCapabilities> crateApiTypesPlatformCapabilitiesDefault();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateApiEngineApiEngineAcceptTransfer({
    required String transferId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(transferId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineApiEngineAcceptTransferConstMeta,
        argValues: [transferId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineApiEngineAcceptTransferConstMeta =>
      const TaskConstMeta(
        debugName: "engine_accept_transfer",
        argNames: ["transferId"],
      );

  @override
  Future<String> crateApiEngineApiEngineCancelTransfer({
    required String transferId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(transferId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineApiEngineCancelTransferConstMeta,
        argValues: [transferId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineApiEngineCancelTransferConstMeta =>
      const TaskConstMeta(
        debugName: "engine_cancel_transfer",
        argNames: ["transferId"],
      );

  @override
  String crateApiEngineApiEngineDeviceId() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineApiEngineDeviceIdConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineApiEngineDeviceIdConstMeta =>
      const TaskConstMeta(debugName: "engine_device_id", argNames: []);

  @override
  String crateApiEngineApiEngineGetDevices() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineApiEngineGetDevicesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineApiEngineGetDevicesConstMeta =>
      const TaskConstMeta(debugName: "engine_get_devices", argNames: []);

  @override
  String crateApiEngineApiEngineGetEvents({required int limit}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(limit, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineApiEngineGetEventsConstMeta,
        argValues: [limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineApiEngineGetEventsConstMeta =>
      const TaskConstMeta(debugName: "engine_get_events", argNames: ["limit"]);

  @override
  String crateApiEngineApiEngineGetProgress({required String transferId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(transferId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineApiEngineGetProgressConstMeta,
        argValues: [transferId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineApiEngineGetProgressConstMeta =>
      const TaskConstMeta(
        debugName: "engine_get_progress",
        argNames: ["transferId"],
      );

  @override
  String crateApiEngineApiEngineGetStreams() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineApiEngineGetStreamsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineApiEngineGetStreamsConstMeta =>
      const TaskConstMeta(debugName: "engine_get_streams", argNames: []);

  @override
  String crateApiEngineApiEngineGetTransfers() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineApiEngineGetTransfersConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineApiEngineGetTransfersConstMeta =>
      const TaskConstMeta(debugName: "engine_get_transfers", argNames: []);

  @override
  Future<String> crateApiEngineApiEngineInit() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineApiEngineInitConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineApiEngineInitConstMeta =>
      const TaskConstMeta(debugName: "engine_init", argNames: []);

  @override
  String crateApiEngineApiEngineLoadSettings() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineApiEngineLoadSettingsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineApiEngineLoadSettingsConstMeta =>
      const TaskConstMeta(debugName: "engine_load_settings", argNames: []);

  @override
  Future<String> crateApiEngineApiEnginePauseTransfer({
    required String transferId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(transferId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineApiEnginePauseTransferConstMeta,
        argValues: [transferId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineApiEnginePauseTransferConstMeta =>
      const TaskConstMeta(
        debugName: "engine_pause_transfer",
        argNames: ["transferId"],
      );

  @override
  Future<String> crateApiEngineApiEngineResumeTransfer({
    required String transferId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(transferId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineApiEngineResumeTransferConstMeta,
        argValues: [transferId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineApiEngineResumeTransferConstMeta =>
      const TaskConstMeta(
        debugName: "engine_resume_transfer",
        argNames: ["transferId"],
      );

  @override
  Future<String> crateApiEngineApiEngineSaveSettings({required String json}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(json, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineApiEngineSaveSettingsConstMeta,
        argValues: [json],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineApiEngineSaveSettingsConstMeta =>
      const TaskConstMeta(
        debugName: "engine_save_settings",
        argNames: ["json"],
      );

  @override
  Future<String> crateApiEngineApiEngineSendClipboard({
    required String deviceId,
    required String text,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(deviceId, serializer);
          sse_encode_String(text, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineApiEngineSendClipboardConstMeta,
        argValues: [deviceId, text],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineApiEngineSendClipboardConstMeta =>
      const TaskConstMeta(
        debugName: "engine_send_clipboard",
        argNames: ["deviceId", "text"],
      );

  @override
  Future<String> crateApiEngineApiEngineSendFiles({
    required String deviceId,
    required List<String> filePaths,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(deviceId, serializer);
          sse_encode_list_String(filePaths, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineApiEngineSendFilesConstMeta,
        argValues: [deviceId, filePaths],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineApiEngineSendFilesConstMeta =>
      const TaskConstMeta(
        debugName: "engine_send_files",
        argNames: ["deviceId", "filePaths"],
      );

  @override
  Future<String> crateApiEngineApiEngineSetDeviceName({required String name}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineApiEngineSetDeviceNameConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineApiEngineSetDeviceNameConstMeta =>
      const TaskConstMeta(
        debugName: "engine_set_device_name",
        argNames: ["name"],
      );

  @override
  String crateApiEngineApiEngineState() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineApiEngineStateConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineApiEngineStateConstMeta =>
      const TaskConstMeta(debugName: "engine_state", argNames: []);

  @override
  Future<void> crateApiEngineApiEngineStop() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineApiEngineStopConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineApiEngineStopConstMeta =>
      const TaskConstMeta(debugName: "engine_stop", argNames: []);

  @override
  String crateApiInitGetBuildInfo() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitGetBuildInfoConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitGetBuildInfoConstMeta =>
      const TaskConstMeta(debugName: "get_build_info", argNames: []);

  @override
  int crateApiInitGetProtocolVersion() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitGetProtocolVersionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitGetProtocolVersionConstMeta =>
      const TaskConstMeta(debugName: "get_protocol_version", argNames: []);

  @override
  String crateApiInitGetVersion() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitGetVersionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitGetVersionConstMeta =>
      const TaskConstMeta(debugName: "get_version", argNames: []);

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  String crateApiInitHealthCheck() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 23)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitHealthCheckConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitHealthCheckConstMeta =>
      const TaskConstMeta(debugName: "health_check", argNames: []);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<PlatformCapabilities> crateApiTypesPlatformCapabilitiesDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_platform_capabilities,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTypesPlatformCapabilitiesDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTypesPlatformCapabilitiesDefaultConstMeta =>
      const TaskConstMeta(
        debugName: "platform_capabilities_default",
        argNames: [],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  PlatformCapabilities dco_decode_platform_capabilities(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return PlatformCapabilities(
      fileTransfer: dco_decode_bool(arr[0]),
      folderTransfer: dco_decode_bool(arr[1]),
      clipboard: dco_decode_bool(arr[2]),
      cameraStream: dco_decode_bool(arr[3]),
      screenShare: dco_decode_bool(arr[4]),
      videoStream: dco_decode_bool(arr[5]),
      audioStream: dco_decode_bool(arr[6]),
      dragDrop: dco_decode_bool(arr[7]),
      shareSheet: dco_decode_bool(arr[8]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  PlatformCapabilities sse_decode_platform_capabilities(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_fileTransfer = sse_decode_bool(deserializer);
    var var_folderTransfer = sse_decode_bool(deserializer);
    var var_clipboard = sse_decode_bool(deserializer);
    var var_cameraStream = sse_decode_bool(deserializer);
    var var_screenShare = sse_decode_bool(deserializer);
    var var_videoStream = sse_decode_bool(deserializer);
    var var_audioStream = sse_decode_bool(deserializer);
    var var_dragDrop = sse_decode_bool(deserializer);
    var var_shareSheet = sse_decode_bool(deserializer);
    return PlatformCapabilities(
      fileTransfer: var_fileTransfer,
      folderTransfer: var_folderTransfer,
      clipboard: var_clipboard,
      cameraStream: var_cameraStream,
      screenShare: var_screenShare,
      videoStream: var_videoStream,
      audioStream: var_audioStream,
      dragDrop: var_dragDrop,
      shareSheet: var_shareSheet,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_platform_capabilities(
    PlatformCapabilities self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.fileTransfer, serializer);
    sse_encode_bool(self.folderTransfer, serializer);
    sse_encode_bool(self.clipboard, serializer);
    sse_encode_bool(self.cameraStream, serializer);
    sse_encode_bool(self.screenShare, serializer);
    sse_encode_bool(self.videoStream, serializer);
    sse_encode_bool(self.audioStream, serializer);
    sse_encode_bool(self.dragDrop, serializer);
    sse_encode_bool(self.shareSheet, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
