// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `with_engine_runtime`, `with_engine`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `EngineHandle`

/// Initialize the UOT engine. Call once at app startup.
Future<String> engineInit() =>
    RustLib.instance.api.crateApiEngineApiEngineInit();

/// Get the current engine state.
String engineState() => RustLib.instance.api.crateApiEngineApiEngineState();

/// Get the device ID.
String engineDeviceId() =>
    RustLib.instance.api.crateApiEngineApiEngineDeviceId();

/// Get all discovered devices as JSON.
String engineGetDevices() =>
    RustLib.instance.api.crateApiEngineApiEngineGetDevices();

/// Get all transfers as JSON.
String engineGetTransfers() =>
    RustLib.instance.api.crateApiEngineApiEngineGetTransfers();

/// Send files to a device. Returns transfer ID or error.
Future<String> engineSendFiles({
  required String deviceId,
  required List<String> filePaths,
}) =>
    RustLib.instance.api.crateApiEngineApiEngineSendFiles(
      deviceId: deviceId,
      filePaths: filePaths,
    );

/// Stop the engine.
Future<void> engineStop() => RustLib.instance.api.crateApiEngineApiEngineStop();

/// Pause a transfer.
Future<String> enginePauseTransfer({required String transferId}) =>
    RustLib.instance.api
        .crateApiEngineApiEnginePauseTransfer(transferId: transferId);

/// Resume a transfer.
Future<String> engineResumeTransfer({required String transferId}) =>
    RustLib.instance.api
        .crateApiEngineApiEngineResumeTransfer(transferId: transferId);

/// Cancel a transfer.
Future<String> engineCancelTransfer({required String transferId}) =>
    RustLib.instance.api
        .crateApiEngineApiEngineCancelTransfer(transferId: transferId);

/// Accept an incoming transfer.
Future<String> engineAcceptTransfer({required String transferId}) =>
    RustLib.instance.api
        .crateApiEngineApiEngineAcceptTransfer(transferId: transferId);

/// Get transfer progress as JSON.
String engineGetProgress({required String transferId}) => RustLib.instance.api
    .crateApiEngineApiEngineGetProgress(transferId: transferId);

/// Set device name.
Future<String> engineSetDeviceName({required String name}) =>
    RustLib.instance.api.crateApiEngineApiEngineSetDeviceName(name: name);

/// Send clipboard text to a device.
Future<String> engineSendClipboard({
  required String deviceId,
  required String text,
}) =>
    RustLib.instance.api.crateApiEngineApiEngineSendClipboard(
      deviceId: deviceId,
      text: text,
    );

/// Get event log (latest N events as JSON).
String engineGetEvents({required int limit}) =>
    RustLib.instance.api.crateApiEngineApiEngineGetEvents(limit: limit);

/// Get active streaming sessions as JSON.
String engineGetStreams() =>
    RustLib.instance.api.crateApiEngineApiEngineGetStreams();

/// Load user settings as JSON.
String engineLoadSettings() =>
    RustLib.instance.api.crateApiEngineApiEngineLoadSettings();

/// Save user settings from JSON.
Future<String> engineSaveSettings({required String json}) =>
    RustLib.instance.api.crateApiEngineApiEngineSaveSettings(json: json);

/// Generate QR invitation JSON string for device pairing.
String engineGenerateQrInvitation({required String pin}) =>
    RustLib.instance.api.crateApiEngineApiEngineGenerateQrInvitation(pin: pin);

/// Parse and validate QR invitation JSON string.
String engineParseQrInvitation({required String json}) =>
    RustLib.instance.api.crateApiEngineApiEngineParseQrInvitation(json: json);

/// Search persistent transfer history with query string.
String engineSearchHistory({required String query}) =>
    RustLib.instance.api.crateApiEngineApiEngineSearchHistory(query: query);

/// Get cumulative lifetime transfer statistics as JSON.
String engineGetStats() =>
    RustLib.instance.api.crateApiEngineApiEngineGetStats();
