// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `with_engine_runtime`, `with_engine`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `EngineHandle`

/// Initialize the UOT engine. Call once at app startup.
Future<String> engineInit() =>
    RustLib.instance.api.crateApiEngineApiEngineInit();

/// Get the current engine state.
String engineState() => RustLib.instance.api.crateApiEngineApiEngineState();

/// Get the device ID.
String engineDeviceId() =>
    RustLib.instance.api.crateApiEngineApiEngineDeviceId();

/// Get all discovered devices as JSON.
String engineGetDevices() =>
    RustLib.instance.api.crateApiEngineApiEngineGetDevices();

/// Get all transfers as JSON.
String engineGetTransfers() =>
    RustLib.instance.api.crateApiEngineApiEngineGetTransfers();

/// Send files to a device. Returns transfer ID or error.
Future<String> engineSendFiles(
        {required String deviceId, required List<String> filePaths}) =>
    RustLib.instance.api.crateApiEngineApiEngineSendFiles(
        deviceId: deviceId, filePaths: filePaths);

/// Stop the engine.
Future<void> engineStop() => RustLib.instance.api.crateApiEngineApiEngineStop();

/// Pause a transfer.
Future<String> enginePauseTransfer({required String transferId}) =>
    RustLib.instance.api
        .crateApiEngineApiEnginePauseTransfer(transferId: transferId);

/// Resume a transfer.
Future<String> engineResumeTransfer({required String transferId}) =>
    RustLib.instance.api
        .crateApiEngineApiEngineResumeTransfer(transferId: transferId);

/// Cancel a transfer.
Future<String> engineCancelTransfer({required String transferId}) =>
    RustLib.instance.api
        .crateApiEngineApiEngineCancelTransfer(transferId: transferId);

/// Accept an incoming transfer.
Future<String> engineAcceptTransfer({required String transferId}) =>
    RustLib.instance.api
        .crateApiEngineApiEngineAcceptTransfer(transferId: transferId);

/// Get transfer progress as JSON.
String engineGetProgress({required String transferId}) => RustLib.instance.api
    .crateApiEngineApiEngineGetProgress(transferId: transferId);

/// Set device name.
Future<String> engineSetDeviceName({required String name}) =>
    RustLib.instance.api.crateApiEngineApiEngineSetDeviceName(name: name);

/// Send clipboard text to a device.
Future<String> engineSendClipboard(
        {required String deviceId, required String text}) =>
    RustLib.instance.api
        .crateApiEngineApiEngineSendClipboard(deviceId: deviceId, text: text);

/// Get event log (latest N events as JSON).
String engineGetEvents({required int limit}) =>
    RustLib.instance.api.crateApiEngineApiEngineGetEvents(limit: limit);

/// Get active streaming sessions as JSON.
String engineGetStreams() =>
    RustLib.instance.api.crateApiEngineApiEngineGetStreams();

/// Start a new media streaming session.
String engineStartStream(
        {required String streamType,
        required String remoteDeviceId,
        required String remoteDeviceName,
        required int port,
        required bool isSender}) =>
    RustLib.instance.api.crateApiEngineApiEngineStartStream(
        streamType: streamType,
        remoteDeviceId: remoteDeviceId,
        remoteDeviceName: remoteDeviceName,
        port: port,
        isSender: isSender);

/// Stop an active media streaming session.
String engineStopStream({required String sessionId}) => RustLib.instance.api
    .crateApiEngineApiEngineStopStream(sessionId: sessionId);

/// Load user settings as JSON.
String engineLoadSettings() =>
    RustLib.instance.api.crateApiEngineApiEngineLoadSettings();

/// Save user settings from JSON.
Future<String> engineSaveSettings({required String json}) =>
    RustLib.instance.api.crateApiEngineApiEngineSaveSettings(json: json);

/// Generate QR invitation JSON string for device pairing.
String engineGenerateQrInvitation({required String pin}) =>
    RustLib.instance.api.crateApiEngineApiEngineGenerateQrInvitation(pin: pin);

/// Parse and validate QR invitation JSON string.
String engineParseQrInvitation({required String json}) =>
    RustLib.instance.api.crateApiEngineApiEngineParseQrInvitation(json: json);

/// Search persistent transfer history with query string.
/// Search transfer history via engine's in-memory store.
String engineSearchHistory({required String query}) =>
    RustLib.instance.api.crateApiEngineApiEngineSearchHistory(query: query);

/// Get cumulative lifetime transfer statistics from engine.
String engineGetStats() =>
    RustLib.instance.api.crateApiEngineApiEngineGetStats();

/// Fallback subnet scan for device discovery.
Future<String> engineSubnetScan() =>
    RustLib.instance.api.crateApiEngineApiEngineSubnetScan();

/// Direct connection to a peer by address (IP:port or IP).
Future<String> engineConnectPeer({required String address}) =>
    RustLib.instance.api.crateApiEngineApiEngineConnectPeer(address: address);

/// Get local IPv4 addresses as JSON list.
String engineGetLocalIps() =>
    RustLib.instance.api.crateApiEngineApiEngineGetLocalIps();

/// Get the actual bound listening port of the local TCP transport engine.
int engineGetListeningPort() =>
    RustLib.instance.api.crateApiEngineApiEngineGetListeningPort();

/// Generate a 6-digit verification PIN with specified TTL in seconds.
String engineGeneratePin({required BigInt ttlSecs}) =>
    RustLib.instance.api.crateApiEngineApiEngineGeneratePin(ttlSecs: ttlSecs);

/// Verify a PIN attempt for a device ID, returning session token on success.
String engineVerifyPin({required String deviceId, required String attempt}) =>
    RustLib.instance.api
        .crateApiEngineApiEngineVerifyPin(deviceId: deviceId, attempt: attempt);

/// Trigger Windows UAC prompt to create firewall rule allowing inbound TCP port 42000.
String engineFixWindowsFirewall() =>
    RustLib.instance.api.crateApiEngineApiEngineFixWindowsFirewall();

/// Encode data payload into animated fountain packets (for zero-network Optical QR transfer).
String engineFountainEncode(
        {required String dataBase64, required int blockSize}) =>
    RustLib.instance.api.crateApiEngineApiEngineFountainEncode(
        dataBase64: dataBase64, blockSize: blockSize);
