// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Get the current version string of the UOT core engine.
String getVersion() => RustLib.instance.api.crateApiInitGetVersion();

/// Get the current protocol version.
int getProtocolVersion() =>
    RustLib.instance.api.crateApiInitGetProtocolVersion();

/// Get detailed build information.
String getBuildInfo() => RustLib.instance.api.crateApiInitGetBuildInfo();

/// Perform a health check on the core engine.
/// Returns a JSON string with status information.
String healthCheck() => RustLib.instance.api.crateApiInitHealthCheck();
