// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ConnectionInfo`, `DeviceInfo`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

/// Platform capability summary.
class PlatformCapabilities {
  /// Whether file transfer is supported.
  final bool fileTransfer;

  /// Whether folder transfer is supported.
  final bool folderTransfer;

  /// Whether clipboard sharing is supported.
  final bool clipboard;

  /// Whether camera streaming is supported.
  final bool cameraStream;

  /// Whether screen sharing is supported.
  final bool screenShare;

  /// Whether video file streaming is supported.
  final bool videoStream;

  /// Whether audio file streaming is supported.
  final bool audioStream;

  /// Whether drag-and-drop is supported.
  final bool dragDrop;

  /// Whether share sheet integration is supported.
  final bool shareSheet;

  const PlatformCapabilities({
    required this.fileTransfer,
    required this.folderTransfer,
    required this.clipboard,
    required this.cameraStream,
    required this.screenShare,
    required this.videoStream,
    required this.audioStream,
    required this.dragDrop,
    required this.shareSheet,
  });

  static Future<PlatformCapabilities> default_() =>
      RustLib.instance.api.crateApiTypesPlatformCapabilitiesDefault();

  @override
  int get hashCode =>
      fileTransfer.hashCode ^
      folderTransfer.hashCode ^
      clipboard.hashCode ^
      cameraStream.hashCode ^
      screenShare.hashCode ^
      videoStream.hashCode ^
      audioStream.hashCode ^
      dragDrop.hashCode ^
      shareSheet.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlatformCapabilities &&
          runtimeType == other.runtimeType &&
          fileTransfer == other.fileTransfer &&
          folderTransfer == other.folderTransfer &&
          clipboard == other.clipboard &&
          cameraStream == other.cameraStream &&
          screenShare == other.screenShare &&
          videoStream == other.videoStream &&
          audioStream == other.audioStream &&
          dragDrop == other.dragDrop &&
          shareSheet == other.shareSheet;
}
